name: yt_flutter_musicapi
description: A Flutter plugin for YouTube Music API that provides music search and related songs functionality using Python backend.
version: 1.0.2
homepage: https://github.com/golanpiyush/yt_flutter_musicapi
repository: https://github.com/golanpiyush/yt_flutter_musicapi
issue_tracker: https://github.com/golanpiyush/yt_flutter_musicapi/issues


environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.3
  build_runner: ^2.5.4
  
  mocktail: ^1.0.4


flutter:
  plugin:
    platforms:
      android:
        package: com.golanpiyush.yt_flutter_musicapi
        pluginClass: YtFlutterMusicapiPlugin
